spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          github:
          - clientId=${GITHUB_CLIENT_ID}
          - clientSecret=${GITHUB_CLIENT_SECRET}

oauth:
  baseurl: ${GITHUB_BASE_URL}