name: SCANNER-SNAPSHOT CI/CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_SERVER_HOST }}
          username: ${{ secrets.API_SERVER_SSH_ID }}
          key: ${{ secrets.API_SERVER_SSH }}
          port: ${{ secrets.API_SERVER_PORT }}
          script: |
            DATE=$(date "+%y.%m.%d")
            docker build -t ${{ secrets.REGISTRY_001 }}/scanner_api_v2:$DATE ./backend-scanner/
            docker push ${{ secrets.REGISTRY_001 }}/scanner_api_v2:$DATE
