name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Docker Build
        run: docker build -t ${{ secrets.REGISTRY }}/oauth-server .

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: docker push ${{ secrets.REGISTRY }}/oauth-server

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_SERVER_HOST }}
          username: ${{ secrets.API_SERVER_SSH_ID }}
          key: ${{ secrets.API_SERVER_SSH }}
          port: ${{ secrets.API_SERVER_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker pull ${{ secrets.REGISTRY }}/oauth-server
            docker compose up -d

